[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable && corepack prepare pnpm@latest --activate && pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "npx prisma migrate deploy || true && node scripts/seed-if-empty.js || true && node dist/src/main.js"
