// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --transpile-only --project tsconfig.seed.json prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI only (migrate/introspect). Supabase's pooled connection (port 6543)
    // can't run DDL or advisory locks, so migrations use the direct connection when
    // DIRECT_URL is set. The app runtime keeps using pooled DATABASE_URL via the
    // driver adapter in src/prisma/prisma.service.ts. Prisma 7 removed `directUrl`,
    // so the equivalent is expressed here. See https://pris.ly/d/config-datasource
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
